### ISSUE TITLE
Test Failures on NonDex due to Flaky Tests

### ISSUE THREAD

**Issue by priyanka-28** [cerner/common-kafka#49]
The tests com.cerner.common.kafka.consumer.ProcessingKafkaConsumerTest.nextRecord_fairProcessing and com.cerner.common.kafka.consumer.ProcessingKafkaConsumerTest.rebalanceListener_onPartitionsAssigned passed using normal maven-test, but showed Non-deterministic behavior under NonDex (https://github.com/TestingResearchIllinois/NonDex) and thus failed. Some error messages are - 

<img width="1246" alt="Screenshot 2022-11-03 at 1 56 15 AM" src="https://user-images.githubusercontent.com/52324780/199662751-b56c16fd-35c7-4683-bb29-a3d05aa44c10.png">

<img width="1242" alt="Screenshot 2022-11-03 at 1 59 05 AM" src="https://user-images.githubusercontent.com/52324780/199663066-ae6d6476-7cab-4517-94da-64d3c50f3312.png">

and after some probing, I found the output from the test is not deterministic.

After the fix, it passes with NonDex-

<img width="1431" alt="Screenshot 2022-11-03 at 2 04 19 AM" src="https://user-images.githubusercontent.com/52324780/199663690-ad33be83-2596-4df4-b539-4037021dd20d.png">

**Comment by noslowerdna** [comment]
Closing this; @priyanka-28  please reopen if you believe there are lingering issues to address.
