### ISSUE TITLE
About Kafka 0.11 support

### ISSUE THREAD

**Issue by Kmotiko** [cerner/common-kafka#6]
Thank you for your great work.
FairAssignor is very useful for me, because StickyAssignor, which is kafka's official assignor, is not work well in my use-case.

Now, I have a question about common-kafka.
Are there any plans to support Kafka 0.11 ? 

In my environment, Kafka 0.11.0.2 is working,  so some problem will be occurred to use FairAssignor.
In Kafka 0.11, Record Header was added,  and I use that feature.
Unfortunately Kafka 0.10 consumer can not receive the record which include Record Header.

I would be grateful if common-kafka support Kafka 0.11.
Please let me know what you think.

**Comment by bbaugher** [comment]
I'm pretty sure if you only want to make use of the FairAssignor you could do so and override the version to use Kafka 0.11. It only makes use of a few kafka classes so I'm guessing you shouldn't have any trouble.

As far as supporting 0.11 goes I'm guessing we won't since 1.0 has been out for several months. We've started some of that [work](https://github.com/cerner/common-kafka/pull/2) but its not complete yet and I'm not certain when we will get to finishing it.

**Comment by Kmotiko** [comment]
Thank you for your reply.

I tried to override the Kafka version with 0.11, and I met the following problem.

```
Exception in thread "main" java.lang.ClassCastException: org.apache.kafka.clients.consumer.internals.PartitionAssignor$Subscription cannot be cast to java.util.List
        at com.cerner.common.kafka.consumer.assignors.FairAssignor.consumersPerTopic(FairAssignor.java:151)
        at com.cerner.common.kafka.consumer.assignors.FairAssignor.assign(FairAssignor.java:62)
...
```

I guess, it is because that there are some differences between 0.10.2.1 and 0.11.0.2 in AbstractPartitionAssignor.
In Kafka 0.10.2.1, AbstractPartitionAssignor#assign is like bellow.
```
public abstract Map<String, List<TopicPartition>> assign(Map<String, Integer> partitionsPerTopic,
                                                             Map<String, List<String>> subscriptions);
```

And In Kafka 0.11.0.2, like bellow.
```
public abstract Map<String, List<TopicPartition>> assign(Map<String, Integer> partitionsPerTopic,
                                                             Map<String, Subscription> subscriptions);
```

The variable type of subscriptions is changed to Subscription Class from List of String, and I think that is the cause of CastException.
To avoid this exception, I tried to implements My FairAssignor extending FairAssignor, but another error, name-crash error,  was occurred.
I feel it is difficult to fix it immediately, so I' ll look for other way to do fairly partition assignment  in my environment.


> As far as supporting 0.11 goes I'm guessing we won't since 1.0 has been out for several months. We've started some of that work but its not complete yet and I'm not certain when we will get to finishing it

I understand. Thank you for information.
I'm looking forward it 😃

**Comment by noslowerdna** [comment]
@Kmotiko It looks like the changes needed for compatibility with Kafka 0.11 are fairly simple, here is updated code that you could use (you will probably want to rename this class if you're using other classes from common-kafka and still need it as a dependency),

https://gist.github.com/noslowerdna/a6c33028c05334dd2d6459022f65e904

**Comment by Kmotiko** [comment]
@noslowerdna 
Thank you  for your updating code.

I tried to fix with minimal change while using common-kafka library,  and so, I feel it is little bit hard.
For now, I only want to use FairAssignor, so your proposal is simple and will work well.

Thank you again. 😄

**Comment by Kmotiko** [comment]
My question was resolved, so I close this issue.
Thank you for your reply @bbaugher @noslowerdna :)
