### ISSUE TITLE
What if I want to connect to other  Kafka version 

### ISSUE THREAD

**Issue by terrycong** [cerner/common-kafka#9]
I would like to connect to my Kafka cluster with below version :
		<dependency>
			<groupId>org.apache.kafka</groupId>
			<artifactId>kafka_2.10</artifactId>
			<version>0.9.0.1</version>
		</dependency>
Do I need to recompile or just replace some of the dependencies please ?

**Comment by mkwhitacre** [comment]
You would need to recompile.  Specifically kafka_2.10 is targeting Scala 2.10 which doesn't maintain API compatibility between versions in the 2.x code stream.

Also I'm not sure you'll be able to just replace dependencies.  I believe we use methods only available in Kafka 0.10 and Kafka sometimes changed its method signatures prior to the 1.0 release.

Semi-related, you should be able to upgrade your cluster to 0.10.2.x and then later upgrade your clients.  If you leave it on the 0.9 log format till all of your clients are upgraded you won't notice a significant difference but benefit from a number of bug fixes.  Then you'll be able to use this client.

**Comment by terrycong** [comment]
thank for your response
